version: "2"

services:
  med_registry_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - med_registry_db:/var/lib/postgresql/data/
    restart: on-failure

  med_registry:
    build: .
    volumes:
      - .:/src
    command: uvicorn src.main:app --host ${APPLICATION_HOST} --port ${DOCKER_EXPOSED_PORT} --reload
    ports:
      - "${APPLICATION_PORT}:${DOCKER_EXPOSED_PORT}"
    env_file:
      - .env
    depends_on:
      - med_registry_db
    environment:
      - WATCHFILES_FORCE_POLLING=true
    restart: on-failure

volumes:
  med_registry_db: null
