"""patient_table

Revision ID: 1eaf033e5f25
Revises: 4bc582e12704
Create Date: 2024-07-29 18:37:36.074926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1eaf033e5f25'
down_revision: Union[str, None] = '4bc582e12704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'patients',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('firstname', sa.Text(), nullable=False),
        sa.Column('lastname', sa.Text(), nullable=False),
        sa.Column('arrival_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
        sa.Column('status', sa.Text(), nullable=False),
        sa.Column('dispensary_id', sa.Integer(), nullable=False),
        sa.Column('room_number', sa.Integer(), nullable=False),
        sa.Column('bunk_number', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['bunk_number', 'room_number', 'dispensary_id'],
                                ['bunk.bunk_number', 'bunk.room_number', 'bunk.dispensary_id'], ),
        sa.ForeignKeyConstraint(['dispensary_id'], ['drug_dispensary.id'], ),
        sa.ForeignKeyConstraint(['room_number', 'dispensary_id'],
                                ['room.room_number', 'room.dispensary_id'], ),
        sa.PrimaryKeyConstraint('id')
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('patients')
	# ### end Alembic commands ###
