"""room_table

Revision ID: ae440e7dda16
Revises: 1f4e9ce8ce1a
Create Date: 2024-07-29 18:21:43.256460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae440e7dda16'
down_revision: Union[str, None] = '1f4e9ce8ce1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_status', sa.Text(), nullable=True),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('dispensary_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dispensary_id'], ['drug_dispensary.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number', 'dispensary_id', name='uix_room_number_dispensary_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    # ### end Alembic commands ###
