"""bunk_table

Revision ID: d8db7fe769fd
Revises: ae440e7dda16
Create Date: 2024-07-29 18:32:04.958492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8db7fe769fd'
down_revision: Union[str, None] = 'ae440e7dda16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bunk_status', sa.Text(), nullable=True),
    sa.Column('bunk_number', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('dispensary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_number', 'dispensary_id'], ['room.room_number', 'room.dispensary_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bunk_number', 'room_number', 'dispensary_id', name='uix_bunk_number')
    )
    op.create_index(op.f('ix_bunk_id'), 'bunk', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bunk_id'), table_name='bunk')
    op.drop_table('bunk')
    # ### end Alembic commands ###
